---
- name: Установка Nginx
  hosts: nginx_servers
  become: yes
  roles:
    - nginx_install

- name: Установка Zabbix Server и Zabbix Web
  hosts: хост
  become: yes
  roles:
    - zabbix_install

- name: Установка Vector
  hosts: filebeat_node
  become: yes
  roles:
    - vector_install

- name: Установка Kibana
  hosts: kibana_server
  become: yes
  roles:
    - kibana_install

- name: Установка Elasticsearch
  hosts: elastic_server
  become: yes
  roles:
    - elasticsearch_install
